#!/bin/bash
submodule_name=$1
submodule_url=$2
git submodule add $submodule_url borne_arcade/projet/$submodule_name
git submodule update --init --recursive --remote borne_arcade/projet/$submodule_name